runtime: python37
api_version: 1
threadsafe: true
service: wishboard-frontend

handlers:
  - url: /
    static_files: /dist/wishboard-frontend/index.html
    upload: dist/index.html
  - url: /
    static_dir: dist/wishboard-frontend
