runtime: nodejs12
#service: wishboard-frontend

handlers:
  - url: /.*
    static_files: dist/wishboard-frontend/index.html
    upload: dist/wishboard-frontend/index.html
  - url: /.*
    static_dir: dist/wishboard-frontend
